Migrate to fusion-core 0.3.0-4 (createPlugin DI API)
fusionjs/fusion-plugin-error-handling pull request #42
Opened 2018-01-18 23:08 UTC by lhorie

Resolves #26

2018-01-18 23:13 UTC, ganemone requested changes

2018-01-18 23:13 UTC, ganemone commented on src/__tests__/index.node.js
> +    .catch(() => {});
I feel like this will make errors hard to discover, since they will be caught and thrown away. I would rather just have an unhandled rejection here

2018-01-18 23:13 UTC, ganemone commented on src/server.js
> +        ctx.body.head.unshift(script);
this is now `ctx.template.head` - we should add a test for this

2018-01-19 00:51 UTC, ganemone approved these changes

2018-01-19 18:35 UTC, lhorie commented
!merge

2018-01-19 18:35 UTC, merged